//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.14 at 01:46:46 ���� CST 
//


package com.winit.label.manager.impl.us.usps.intl.model.ext.request;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.lable.usa.usps.data package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.lable.usa.usps.data
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RequestManifest }
     * 
     */
    public RequestManifest createManifest() {
        return new RequestManifest();
    }

    /**
     * Create an instance of {@link RequestManifest.Package }
     * 
     */
    public RequestManifest.Package createManifestPackage() {
        return new RequestManifest.Package();
    }

    /**
     * Create an instance of {@link RequestManifest.Dispatch }
     * 
     */
    public RequestManifest.Dispatch createManifestDispatch() {
        return new RequestManifest.Dispatch();
    }

    /**
     * Create an instance of {@link RequestManifest.Package.Item }
     * 
     */
    public RequestManifest.Package.Item createManifestPackageItem() {
        return new RequestManifest.Package.Item();
    }

}
