package com.winit.label.manager.impl.us.usps.intl.model.ext.request;
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.14 at 01:46:46 ���� CST 
//

//@javax.xml.bind.annotation.XmlSchema(
//		 xmlns = { 
//			      @javax.xml.bind.annotation.XmlNs(prefix = "customns", 
//			         namespaceURI="http://test/")
//			   },
//namespace = "mailerdataformatf08.xsd",
//elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
//package com.lable.usa.usps.data;
