package com.winit.label.manager.impl.us.usps.intl.model;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.12
 * 2014-09-22T15:51:41.212+08:00
 * Generated source version: 2.7.12
 * 
 */
@WebService(targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/", name = "ProcessPackageSoap")
@XmlSeeAlso({ObjectFactory.class,com.winit.label.manager.impl.us.usps.intl.model.ext.request.ObjectFactory.class,com.winit.label.manager.impl.us.usps.intl.model.ext.response.ObjectFactory.class})
public interface ProcessPackageSoap {

    /**
     * Retrieves shipment history for the location.
     */
    @WebResult(name = "GetShipmentHistoryResult", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
    @RequestWrapper(localName = "GetShipmentHistory", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/", className = "com.winit.label.manager.impl.us.usps.intl.GetShipmentHistory")
    @WebMethod(operationName = "GetShipmentHistory", action = "http://www.usps-cpas.com/usps-cpas/GSSAPI/GetShipmentHistory")
    @ResponseWrapper(localName = "GetShipmentHistoryResponse", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/", className = "com.winit.label.manager.impl.us.usps.intl.GetShipmentHistoryResponse")
    public com.winit.label.manager.impl.us.usps.intl.model.GetShipmentHistoryResponse.GetShipmentHistoryResult getShipmentHistory(
        @WebParam(name = "StartDate", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
        java.lang.String startDate,
        @WebParam(name = "EndDate", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
        java.lang.String endDate,
        @WebParam(name = "AccessToken", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
        java.lang.String accessToken
    );

    /**
     * Returns a list of all destination locations that are available for a mailer.
     */
    @WebResult(name = "GetDestinationLocationsResult", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
    @RequestWrapper(localName = "GetDestinationLocations", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/", className = "com.winit.label.manager.impl.us.usps.intl.GetDestinationLocations")
    @WebMethod(operationName = "GetDestinationLocations", action = "http://www.usps-cpas.com/usps-cpas/GSSAPI/GetDestinationLocations")
    @ResponseWrapper(localName = "GetDestinationLocationsResponse", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/", className = "com.winit.label.manager.impl.us.usps.intl.GetDestinationLocationsResponse")
    public com.winit.label.manager.impl.us.usps.intl.model.DestinationLocationsResult getDestinationLocations(
        @WebParam(name = "AccessToken", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
        java.lang.String accessToken
    );

    /**
     * Removes a package from the open dispatch.
     */
    @WebResult(name = "RemovePackageFromOpenDispatchResult", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
    @RequestWrapper(localName = "RemovePackageFromOpenDispatch", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/", className = "com.winit.label.manager.impl.us.usps.intl.RemovePackageFromOpenDispatch")
    @WebMethod(operationName = "RemovePackageFromOpenDispatch", action = "http://www.usps-cpas.com/usps-cpas/GSSAPI/RemovePackageFromOpenDispatch")
    @ResponseWrapper(localName = "RemovePackageFromOpenDispatchResponse", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/", className = "com.winit.label.manager.impl.us.usps.intl.RemovePackageFromOpenDispatchResponse")
    public com.winit.label.manager.impl.us.usps.intl.model.CommonResult removePackageFromOpenDispatch(
        @WebParam(name = "PackageID", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
        java.lang.String packageID,
        @WebParam(name = "MailingAgentID", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
        java.lang.String mailingAgentID,
        @WebParam(name = "BoxNumber", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
        int boxNumber,
        @WebParam(name = "AccessToken", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
        java.lang.String accessToken
    );

    /**
     * Retrieves frozen dispatch package details.
     */
    @WebResult(name = "RetrieveFrozenDispatchPackagesInfoResult", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
    @RequestWrapper(localName = "RetrieveFrozenDispatchPackagesInfo", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/", className = "com.winit.label.manager.impl.us.usps.intl.RetrieveFrozenDispatchPackagesInfo")
    @WebMethod(operationName = "RetrieveFrozenDispatchPackagesInfo", action = "http://www.usps-cpas.com/usps-cpas/GSSAPI/RetrieveFrozenDispatchPackagesInfo")
    @ResponseWrapper(localName = "RetrieveFrozenDispatchPackagesInfoResponse", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/", className = "com.winit.label.manager.impl.us.usps.intl.RetrieveFrozenDispatchPackagesInfoResponse")
    public com.winit.label.manager.impl.us.usps.intl.model.FrozenDispatchPackagesResult retrieveFrozenDispatchPackagesInfo(
        @WebParam(name = "FreezeDispatchID", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
        java.lang.String freezeDispatchID,
        @WebParam(name = "AccessToken", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
        java.lang.String accessToken
    );

    /**
     * Allow a mailer to query for the postage amount, prior to processing a package.
     */
    @WebResult(name = "CalculatePostageResult", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
    @RequestWrapper(localName = "CalculatePostage", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/", className = "com.winit.label.manager.impl.us.usps.intl.CalculatePostage")
    @WebMethod(operationName = "CalculatePostage", action = "http://www.usps-cpas.com/usps-cpas/GSSAPI/CalculatePostage")
    @ResponseWrapper(localName = "CalculatePostageResponse", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/", className = "com.winit.label.manager.impl.us.usps.intl.CalculatePostageResponse")
    public com.winit.label.manager.impl.us.usps.intl.model.CalculatePostageResult calculatePostage(
        @WebParam(name = "xmlDoc", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
        com.winit.label.manager.impl.us.usps.intl.model.CalculatePostage.XmlDoc xmlDoc,
        @WebParam(name = "AccessToken", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
        java.lang.String accessToken
    );

    /**
     * Freezes the dispatch for a given location.
     */
    @WebResult(name = "FreezeDispatchResult", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
    @RequestWrapper(localName = "FreezeDispatch", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/", className = "com.winit.label.manager.impl.us.usps.intl.FreezeDispatch")
    @WebMethod(operationName = "FreezeDispatch", action = "http://www.usps-cpas.com/usps-cpas/GSSAPI/FreezeDispatch")
    @ResponseWrapper(localName = "FreezeDispatchResponse", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/", className = "com.winit.label.manager.impl.us.usps.intl.FreezeDispatchResponse")
    public com.winit.label.manager.impl.us.usps.intl.model.FrozenDispatchResult freezeDispatch(
        @WebParam(name = "FreezeDispatchID", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
        java.lang.String freezeDispatchID,
        @WebParam(name = "AccessToken", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
        java.lang.String accessToken
    );

    /**
     * Processes a package to a destination location. Used by mailers who use multiple destination locations. 
     */
    @WebResult(name = "ProcessThePackageToDestinationLocationResult", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
    @RequestWrapper(localName = "ProcessThePackageToDestinationLocation", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/", className = "com.winit.label.manager.impl.us.usps.intl.ProcessThePackageToDestinationLocation")
    @WebMethod(operationName = "ProcessThePackageToDestinationLocation", action = "http://www.usps-cpas.com/usps-cpas/GSSAPI/ProcessThePackageToDestinationLocation")
    @ResponseWrapper(localName = "ProcessThePackageToDestinationLocationResponse", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/", className = "com.winit.label.manager.impl.us.usps.intl.ProcessThePackageToDestinationLocationResponse")
    public com.winit.label.manager.impl.us.usps.intl.model.CommonResult processThePackageToDestinationLocation(
        @WebParam(name = "PackageID", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
        java.lang.String packageID,
        @WebParam(name = "MailingAgentID", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
        java.lang.String mailingAgentID,
        @WebParam(name = "BoxNumber", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
        int boxNumber,
        @WebParam(name = "DestinationLocationID", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
        java.lang.String destinationLocationID,
        @WebParam(name = "AccessToken", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
        java.lang.String accessToken
    );

    /**
     * Accepts package data from a mailer in the predefined XML format and processes it.
     */
    @WebResult(name = "LoadAndProcessPackageDataResult", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
    @RequestWrapper(localName = "LoadAndProcessPackageData", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/", className = "com.winit.label.manager.impl.us.usps.intl.LoadAndProcessPackageData")
    @WebMethod(operationName = "LoadAndProcessPackageData", action = "http://www.usps-cpas.com/usps-cpas/GSSAPI/LoadAndProcessPackageData")
    @ResponseWrapper(localName = "LoadAndProcessPackageDataResponse", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/", className = "com.winit.label.manager.impl.us.usps.intl.LoadAndProcessPackageDataResponse")
    public com.winit.label.manager.impl.us.usps.intl.model.LoadAndProcessPackageDataResponse.LoadAndProcessPackageDataResult loadAndProcessPackageData(
        @WebParam(name = "xmlDoc", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
        com.winit.label.manager.impl.us.usps.intl.model.LoadAndProcessPackageData.XmlDoc xmlDoc,
        @WebParam(name = "AccessToken", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
        java.lang.String accessToken
    );

    /**
     * Generates the requested report for a specific mailing agent, location, and time period.
     */
    @WebResult(name = "GenerateActivityReportResult", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
    @RequestWrapper(localName = "GenerateActivityReport", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/", className = "com.winit.label.manager.impl.us.usps.intl.GenerateActivityReport")
    @WebMethod(operationName = "GenerateActivityReport", action = "http://www.usps-cpas.com/usps-cpas/GSSAPI/GenerateActivityReport")
    @ResponseWrapper(localName = "GenerateActivityReportResponse", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/", className = "com.winit.label.manager.impl.us.usps.intl.GenerateActivityReportResponse")
    public com.winit.label.manager.impl.us.usps.intl.model.GenerateReportResult generateActivityReport(
        @WebParam(name = "MailingAgentID", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
        java.lang.String mailingAgentID,
        @WebParam(name = "LocationID", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
        java.lang.String locationID,
        @WebParam(name = "StartDate", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
        java.lang.String startDate,
        @WebParam(name = "StopDate", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
        java.lang.String stopDate,
        @WebParam(name = "ReportID", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
        java.lang.String reportID,
        @WebParam(name = "AccessToken", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
        java.lang.String accessToken
    );

    /**
     * For GSS support use only. Refreshes the Web Component.
     */
    @WebResult(name = "RefreshWebComponentResult", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
    @RequestWrapper(localName = "RefreshWebComponent", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/", className = "com.winit.label.manager.impl.us.usps.intl.RefreshWebComponent")
    @WebMethod(operationName = "RefreshWebComponent", action = "http://www.usps-cpas.com/usps-cpas/GSSAPI/RefreshWebComponent")
    @ResponseWrapper(localName = "RefreshWebComponentResponse", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/", className = "com.winit.label.manager.impl.us.usps.intl.RefreshWebComponentResponse")
    public boolean refreshWebComponent(
        @WebParam(name = "Val", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
        java.lang.String val
    );

    /**
     * Retrieves the history of tracking events for a package.
     */
    @WebResult(name = "TrackPackageResult", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
    @RequestWrapper(localName = "TrackPackage", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/", className = "com.winit.label.manager.impl.us.usps.intl.TrackPackage")
    @WebMethod(operationName = "TrackPackage", action = "http://www.usps-cpas.com/usps-cpas/GSSAPI/TrackPackage")
    @ResponseWrapper(localName = "TrackPackageResponse", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/", className = "com.winit.label.manager.impl.us.usps.intl.TrackPackageResponse")
    public com.winit.label.manager.impl.us.usps.intl.model.TrackResult trackPackage(
        @WebParam(name = "PackageID", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
        java.lang.String packageID,
        @WebParam(name = "MailingAgentID", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
        java.lang.String mailingAgentID,
        @WebParam(name = "BoxNumber", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
        int boxNumber,
        @WebParam(name = "AccessToken", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
        java.lang.String accessToken
    );

    /**
     * Retrieves labels for a specified package in JPG or PNG image format.
     */
    @WebResult(name = "GetImageLabelsForPackageResult", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
    @RequestWrapper(localName = "GetImageLabelsForPackage", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/", className = "com.winit.label.manager.impl.us.usps.intl.GetImageLabelsForPackage")
    @WebMethod(operationName = "GetImageLabelsForPackage", action = "http://www.usps-cpas.com/usps-cpas/GSSAPI/GetImageLabelsForPackage")
    @ResponseWrapper(localName = "GetImageLabelsForPackageResponse", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/", className = "com.winit.label.manager.impl.us.usps.intl.GetImageLabelsForPackageResponse")
    public com.winit.label.manager.impl.us.usps.intl.model.LabelResult getImageLabelsForPackage(
        @WebParam(name = "PackageID", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
        java.lang.String packageID,
        @WebParam(name = "MailingAgentID", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
        java.lang.String mailingAgentID,
        @WebParam(name = "BoxNumber", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
        int boxNumber,
        @WebParam(name = "FileFormat", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
        java.lang.String fileFormat,
        @WebParam(name = "AccessToken", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
        java.lang.String accessToken
    );

    /**
     * Freezes the dispatch for a given location.
     */
    @WebResult(name = "FreezeDispatchForLocationResult", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
    @RequestWrapper(localName = "FreezeDispatchForLocation", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/", className = "com.winit.label.manager.impl.us.usps.intl.FreezeDispatchForLocation")
    @WebMethod(operationName = "FreezeDispatchForLocation", action = "http://www.usps-cpas.com/usps-cpas/GSSAPI/FreezeDispatchForLocation")
    @ResponseWrapper(localName = "FreezeDispatchForLocationResponse", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/", className = "com.winit.label.manager.impl.us.usps.intl.FreezeDispatchForLocationResponse")
    public com.winit.label.manager.impl.us.usps.intl.model.FrozenDispatchResult freezeDispatchForLocation(
        @WebParam(name = "FreezeDispatchID", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
        java.lang.String freezeDispatchID,
        @WebParam(name = "DestinationLocationID", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
        java.lang.String destinationLocationID,
        @WebParam(name = "AccessToken", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
        java.lang.String accessToken
    );

    /**
     * Removes a package from a frozen dispatch.
     */
    @WebResult(name = "RemovePackageFromFrozenDispatchResult", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
    @RequestWrapper(localName = "RemovePackageFromFrozenDispatch", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/", className = "com.winit.label.manager.impl.us.usps.intl.RemovePackageFromFrozenDispatch")
    @WebMethod(operationName = "RemovePackageFromFrozenDispatch", action = "http://www.usps-cpas.com/usps-cpas/GSSAPI/RemovePackageFromFrozenDispatch")
    @ResponseWrapper(localName = "RemovePackageFromFrozenDispatchResponse", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/", className = "com.winit.label.manager.impl.us.usps.intl.RemovePackageFromFrozenDispatchResponse")
    public com.winit.label.manager.impl.us.usps.intl.model.CommonResult removePackageFromFrozenDispatch(
        @WebParam(name = "FreezeDispatchID", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
        java.lang.String freezeDispatchID,
        @WebParam(name = "PackageID", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
        java.lang.String packageID,
        @WebParam(name = "MailingAgentID", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
        java.lang.String mailingAgentID,
        @WebParam(name = "BoxNumber", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
        int boxNumber,
        @WebParam(name = "AccessToken", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
        java.lang.String accessToken
    );

    /**
     * Returns a list of all required reports that are available for a dispatch.
     */
    @WebResult(name = "GetRequiredReportsForDispatchResult", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
    @RequestWrapper(localName = "GetRequiredReportsForDispatch", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/", className = "com.winit.label.manager.impl.us.usps.intl.GetRequiredReportsForDispatch")
    @WebMethod(operationName = "GetRequiredReportsForDispatch", action = "http://www.usps-cpas.com/usps-cpas/GSSAPI/GetRequiredReportsForDispatch")
    @ResponseWrapper(localName = "GetRequiredReportsForDispatchResponse", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/", className = "com.winit.label.manager.impl.us.usps.intl.GetRequiredReportsForDispatchResponse")
    public com.winit.label.manager.impl.us.usps.intl.model.GetAvailableReportResult getRequiredReportsForDispatch(
        @WebParam(name = "DispatchID", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
        java.lang.String dispatchID,
        @WebParam(name = "AccessToken", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
        java.lang.String accessToken
    );

    /**
     * Search for a processed package.
     */
    @WebResult(name = "SearchForProcessedPackageResult", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
    @RequestWrapper(localName = "SearchForProcessedPackage", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/", className = "com.winit.label.manager.impl.us.usps.intl.SearchForProcessedPackage")
    @WebMethod(operationName = "SearchForProcessedPackage", action = "http://www.usps-cpas.com/usps-cpas/GSSAPI/SearchForProcessedPackage")
    @ResponseWrapper(localName = "SearchForProcessedPackageResponse", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/", className = "com.winit.label.manager.impl.us.usps.intl.SearchForProcessedPackageResponse")
    public com.winit.label.manager.impl.us.usps.intl.model.SearchForProcessedPackageResponse.SearchForProcessedPackageResult searchForProcessedPackage(
        @WebParam(name = "AccessToken", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
        java.lang.String accessToken,
        @WebParam(name = "PackageID", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
        java.lang.String packageID,
        @WebParam(name = "OrderID", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
        java.lang.String orderID,
        @WebParam(name = "RecipientLastName", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
        java.lang.String recipientLastName,
        @WebParam(name = "RecipientFirstName", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
        java.lang.String recipientFirstName,
        @WebParam(name = "RecipientBusinessName", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
        java.lang.String recipientBusinessName,
        @WebParam(name = "RecipientCountryCode", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
        java.lang.String recipientCountryCode
    );

    /**
     * Logs out the user.
     */
    @WebResult(name = "LogoutUserResult", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
    @RequestWrapper(localName = "LogoutUser", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/", className = "com.winit.label.manager.impl.us.usps.intl.LogoutUser")
    @WebMethod(operationName = "LogoutUser", action = "http://www.usps-cpas.com/usps-cpas/GSSAPI/LogoutUser")
    @ResponseWrapper(localName = "LogoutUserResponse", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/", className = "com.winit.label.manager.impl.us.usps.intl.LogoutUserResponse")
    public com.winit.label.manager.impl.us.usps.intl.model.CommonResult logoutUser(
        @WebParam(name = "AccessToken", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
        java.lang.String accessToken
    );

    /**
     * Retrieves current dispatch for a location.
     */
    @WebResult(name = "GetCurrentDispatchResult", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
    @RequestWrapper(localName = "GetCurrentDispatch", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/", className = "com.winit.label.manager.impl.us.usps.intl.GetCurrentDispatch")
    @WebMethod(operationName = "GetCurrentDispatch", action = "http://www.usps-cpas.com/usps-cpas/GSSAPI/GetCurrentDispatch")
    @ResponseWrapper(localName = "GetCurrentDispatchResponse", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/", className = "com.winit.label.manager.impl.us.usps.intl.GetCurrentDispatchResponse")
    public com.winit.label.manager.impl.us.usps.intl.model.GetCurrentDispatchResponse.GetCurrentDispatchResult getCurrentDispatch(
        @WebParam(name = "AccessToken", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
        java.lang.String accessToken,
        @WebParam(name = "DestinationLocationID", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
        java.lang.String destinationLocationID
    );

    /**
     * Verifies the GXG package for processing, with destination location ID as an additional parameter.
     */
    @WebResult(name = "VerifyGXGPackageToDestinationLocationResult", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
    @RequestWrapper(localName = "VerifyGXGPackageToDestinationLocation", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/", className = "com.winit.label.manager.impl.us.usps.intl.VerifyGXGPackageToDestinationLocation")
    @WebMethod(operationName = "VerifyGXGPackageToDestinationLocation", action = "http://www.usps-cpas.com/usps-cpas/GSSAPI/VerifyGXGPackageToDestinationLocation")
    @ResponseWrapper(localName = "VerifyGXGPackageToDestinationLocationResponse", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/", className = "com.winit.label.manager.impl.us.usps.intl.VerifyGXGPackageToDestinationLocationResponse")
    public com.winit.label.manager.impl.us.usps.intl.model.VerifyGXGPackageToDestinationLocationResponse.VerifyGXGPackageToDestinationLocationResult verifyGXGPackageToDestinationLocation(
        @WebParam(name = "PackageID", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
        java.lang.String packageID,
        @WebParam(name = "MailingAgentID", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
        java.lang.String mailingAgentID,
        @WebParam(name = "BoxNumber", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
        int boxNumber,
        @WebParam(name = "DestinationLocationID", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
        java.lang.String destinationLocationID,
        @WebParam(name = "GXGRequest", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
        com.winit.label.manager.impl.us.usps.intl.model.VerifyGXGPackageToDestinationLocation.GXGRequest gxgRequest,
        @WebParam(name = "AccessToken", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
        java.lang.String accessToken
    );

    /**
     * Get Expected Ship Date
     */
    @WebResult(name = "GetExpectedShipDateResult", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
    @RequestWrapper(localName = "GetExpectedShipDate", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/", className = "com.winit.label.manager.impl.us.usps.intl.GetExpectedShipDate")
    @WebMethod(operationName = "GetExpectedShipDate", action = "http://www.usps-cpas.com/usps-cpas/GSSAPI/GetExpectedShipDate")
    @ResponseWrapper(localName = "GetExpectedShipDateResponse", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/", className = "com.winit.label.manager.impl.us.usps.intl.GetExpectedShipDateResponse")
    public com.winit.label.manager.impl.us.usps.intl.model.ExpectedShipResult getExpectedShipDate(
        @WebParam(name = "DestinationLocationID", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
        java.lang.String destinationLocationID,
        @WebParam(name = "AccessToken", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
        java.lang.String accessToken
    );

    /**
     * Accepts package data from a mailer in the predefined XML format. Overwrites previous version if reloaded.
     */
    @WebResult(name = "LoadPackageDataResult", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
    @RequestWrapper(localName = "LoadPackageData", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/", className = "com.winit.label.manager.impl.us.usps.intl.LoadPackageData")
    @WebMethod(operationName = "LoadPackageData", action = "http://www.usps-cpas.com/usps-cpas/GSSAPI/LoadPackageData")
    @ResponseWrapper(localName = "LoadPackageDataResponse", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/", className = "com.winit.label.manager.impl.us.usps.intl.LoadPackageDataResponse")
    public com.winit.label.manager.impl.us.usps.intl.model.LoadPackageDataResponse.LoadPackageDataResult loadPackageData(
        @WebParam(name = "xmlDoc", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
        com.winit.label.manager.impl.us.usps.intl.model.LoadPackageData.XmlDoc xmlDoc,
        @WebParam(name = "AccessToken", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
        java.lang.String accessToken
    );

    /**
     * Removes a labeled package from further processing. Used by labeling locations only. 
     */
    @WebResult(name = "RemoveLabeledPackageResult", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
    @RequestWrapper(localName = "RemoveLabeledPackage", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/", className = "com.winit.label.manager.impl.us.usps.intl.RemoveLabeledPackage")
    @WebMethod(operationName = "RemoveLabeledPackage", action = "http://www.usps-cpas.com/usps-cpas/GSSAPI/RemoveLabeledPackage")
    @ResponseWrapper(localName = "RemoveLabeledPackageResponse", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/", className = "com.winit.label.manager.impl.us.usps.intl.RemoveLabeledPackageResponse")
    public com.winit.label.manager.impl.us.usps.intl.model.CommonResult removeLabeledPackage(
        @WebParam(name = "PackageID", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
        java.lang.String packageID,
        @WebParam(name = "BoxNumber", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
        int boxNumber,
        @WebParam(name = "AccessToken", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
        java.lang.String accessToken
    );

    /**
     * Generates the Volume & Postage report for a specified mailing agent, location, and time period.
     */
    @WebResult(name = "GenerateVolumePostageReportResult", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
    @RequestWrapper(localName = "GenerateVolumePostageReport", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/", className = "com.winit.label.manager.impl.us.usps.intl.GenerateVolumePostageReport")
    @WebMethod(operationName = "GenerateVolumePostageReport", action = "http://www.usps-cpas.com/usps-cpas/GSSAPI/GenerateVolumePostageReport")
    @ResponseWrapper(localName = "GenerateVolumePostageReportResponse", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/", className = "com.winit.label.manager.impl.us.usps.intl.GenerateVolumePostageReportResponse")
    public com.winit.label.manager.impl.us.usps.intl.model.GenerateReportResult generateVolumePostageReport(
        @WebParam(name = "MailingAgentID", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
        java.lang.String mailingAgentID,
        @WebParam(name = "LocationID", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
        java.lang.String locationID,
        @WebParam(name = "IncludeDestinationCountry", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
        int includeDestinationCountry,
        @WebParam(name = "StartDate", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
        java.lang.String startDate,
        @WebParam(name = "StopDate", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
        java.lang.String stopDate,
        @WebParam(name = "ReportID", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
        java.lang.String reportID,
        @WebParam(name = "AccessToken", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
        java.lang.String accessToken
    );

    /**
     * Freezes the open dispatch for the mailer�s location.
     */
    @WebResult(name = "AddPackageToFrozenDispatchResult", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
    @RequestWrapper(localName = "AddPackageToFrozenDispatch", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/", className = "com.winit.label.manager.impl.us.usps.intl.AddPackageToFrozenDispatch")
    @WebMethod(operationName = "AddPackageToFrozenDispatch", action = "http://www.usps-cpas.com/usps-cpas/GSSAPI/AddPackageToFrozenDispatch")
    @ResponseWrapper(localName = "AddPackageToFrozenDispatchResponse", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/", className = "com.winit.label.manager.impl.us.usps.intl.AddPackageToFrozenDispatchResponse")
    public com.winit.label.manager.impl.us.usps.intl.model.CommonResult addPackageToFrozenDispatch(
        @WebParam(name = "FreezeDispatchID", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
        java.lang.String freezeDispatchID,
        @WebParam(name = "PackageID", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
        java.lang.String packageID,
        @WebParam(name = "AccessToken", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
        java.lang.String accessToken
    );

    /**
     * Retrieves all frozen dispatches for the location.
     */
    @WebResult(name = "RetrieveFrozenDispatchesInfoResult", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
    @RequestWrapper(localName = "RetrieveFrozenDispatchesInfo", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/", className = "com.winit.label.manager.impl.us.usps.intl.RetrieveFrozenDispatchesInfo")
    @WebMethod(operationName = "RetrieveFrozenDispatchesInfo", action = "http://www.usps-cpas.com/usps-cpas/GSSAPI/RetrieveFrozenDispatchesInfo")
    @ResponseWrapper(localName = "RetrieveFrozenDispatchesInfoResponse", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/", className = "com.winit.label.manager.impl.us.usps.intl.RetrieveFrozenDispatchesInfoResponse")
    public com.winit.label.manager.impl.us.usps.intl.model.FrozenDispatchesResult retrieveFrozenDispatchesInfo(
        @WebParam(name = "AccessToken", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
        java.lang.String accessToken
    );

    /**
     * Set Expected Ship Date
     */
    @WebResult(name = "SetExpectedShipDateResult", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
    @RequestWrapper(localName = "SetExpectedShipDate", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/", className = "com.winit.label.manager.impl.us.usps.intl.SetExpectedShipDate")
    @WebMethod(operationName = "SetExpectedShipDate", action = "http://www.usps-cpas.com/usps-cpas/GSSAPI/SetExpectedShipDate")
    @ResponseWrapper(localName = "SetExpectedShipDateResponse", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/", className = "com.winit.label.manager.impl.us.usps.intl.SetExpectedShipDateResponse")
    public com.winit.label.manager.impl.us.usps.intl.model.CommonResult setExpectedShipDate(
        @WebParam(name = "DestinationLocationID", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
        java.lang.String destinationLocationID,
        @WebParam(name = "ExpectedShipDate", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
        java.lang.String expectedShipDate,
        @WebParam(name = "AccessToken", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
        java.lang.String accessToken
    );

    /**
     * Verifies the GXG package for processing.
     */
    @WebResult(name = "VerifyGXGPackageResult", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
    @RequestWrapper(localName = "VerifyGXGPackage", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/", className = "com.winit.label.manager.impl.us.usps.intl.VerifyGXGPackage")
    @WebMethod(operationName = "VerifyGXGPackage", action = "http://www.usps-cpas.com/usps-cpas/GSSAPI/VerifyGXGPackage")
    @ResponseWrapper(localName = "VerifyGXGPackageResponse", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/", className = "com.winit.label.manager.impl.us.usps.intl.VerifyGXGPackageResponse")
    public com.winit.label.manager.impl.us.usps.intl.model.VerifyGXGPackageResponse.VerifyGXGPackageResult verifyGXGPackage(
        @WebParam(name = "PackageID", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
        java.lang.String packageID,
        @WebParam(name = "MailingAgentID", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
        java.lang.String mailingAgentID,
        @WebParam(name = "BoxNumber", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
        int boxNumber,
        @WebParam(name = "GXGRequest", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
        com.winit.label.manager.impl.us.usps.intl.model.VerifyGXGPackage.GXGRequest gxgRequest,
        @WebParam(name = "AccessToken", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
        java.lang.String accessToken
    );

    /**
     * Returns a list of all reports that are available for a dispatch.
     */
    @WebResult(name = "GetAvailableReportsForDispatchResult", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
    @RequestWrapper(localName = "GetAvailableReportsForDispatch", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/", className = "com.winit.label.manager.impl.us.usps.intl.GetAvailableReportsForDispatch")
    @WebMethod(operationName = "GetAvailableReportsForDispatch", action = "http://www.usps-cpas.com/usps-cpas/GSSAPI/GetAvailableReportsForDispatch")
    @ResponseWrapper(localName = "GetAvailableReportsForDispatchResponse", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/", className = "com.winit.label.manager.impl.us.usps.intl.GetAvailableReportsForDispatchResponse")
    public com.winit.label.manager.impl.us.usps.intl.model.GetAvailableReportResult getAvailableReportsForDispatch(
        @WebParam(name = "DispatchID", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
        java.lang.String dispatchID,
        @WebParam(name = "AccessToken", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
        java.lang.String accessToken
    );

    /**
     * Lookup harmonization number for common description.
     */
    @WebResult(name = "LookupHSForCommonDescriptionResult", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
    @RequestWrapper(localName = "LookupHSForCommonDescription", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/", className = "com.winit.label.manager.impl.us.usps.intl.LookupHSForCommonDescription")
    @WebMethod(operationName = "LookupHSForCommonDescription", action = "http://www.usps-cpas.com/usps-cpas/GSSAPI/LookupHSForCommonDescription")
    @ResponseWrapper(localName = "LookupHSForCommonDescriptionResponse", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/", className = "com.winit.label.manager.impl.us.usps.intl.LookupHSForCommonDescriptionResponse")
    public com.winit.label.manager.impl.us.usps.intl.model.LookupHSForCommonDescriptionResponse.LookupHSForCommonDescriptionResult lookupHSForCommonDescription(
        @WebParam(name = "SearchText", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
        java.lang.String searchText,
        @WebParam(name = "MatchLevel", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
        java.lang.String matchLevel,
        @WebParam(name = "AccessToken", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
        java.lang.String accessToken
    );

    /**
     * Lookup harmonization number for legal description.
     */
    @WebResult(name = "LookupHSForLegalDescriptionResult", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
    @RequestWrapper(localName = "LookupHSForLegalDescription", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/", className = "com.winit.label.manager.impl.us.usps.intl.LookupHSForLegalDescription")
    @WebMethod(operationName = "LookupHSForLegalDescription", action = "http://www.usps-cpas.com/usps-cpas/GSSAPI/LookupHSForLegalDescription")
    @ResponseWrapper(localName = "LookupHSForLegalDescriptionResponse", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/", className = "com.winit.label.manager.impl.us.usps.intl.LookupHSForLegalDescriptionResponse")
    public com.winit.label.manager.impl.us.usps.intl.model.LookupHSForLegalDescriptionResponse.LookupHSForLegalDescriptionResult lookupHSForLegalDescription(
        @WebParam(name = "CountryOfImport", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
        java.lang.String countryOfImport,
        @WebParam(name = "SearchText", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
        java.lang.String searchText,
        @WebParam(name = "DateOfImport", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
        java.lang.String dateOfImport,
        @WebParam(name = "ClassificationType", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
        java.lang.String classificationType,
        @WebParam(name = "MatchLevel", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
        java.lang.String matchLevel,
        @WebParam(name = "SearchType", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
        java.lang.String searchType,
        @WebParam(name = "AccessToken", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
        java.lang.String accessToken
    );

    /**
     * Generates the requested report for a closed dispatch.
     */
    @WebResult(name = "GenerateReportResult", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
    @RequestWrapper(localName = "GenerateReport", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/", className = "com.winit.label.manager.impl.us.usps.intl.GenerateReport")
    @WebMethod(operationName = "GenerateReport", action = "http://www.usps-cpas.com/usps-cpas/GSSAPI/GenerateReport")
    @ResponseWrapper(localName = "GenerateReportResponse", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/", className = "com.winit.label.manager.impl.us.usps.intl.GenerateReportResponse")
    public com.winit.label.manager.impl.us.usps.intl.model.GenerateReportResult generateReport(
        @WebParam(name = "DispatchID", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
        java.lang.String dispatchID,
        @WebParam(name = "ReportID", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
        java.lang.String reportID,
        @WebParam(name = "AccessToken", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
        java.lang.String accessToken
    );

    /**
     * Sets the Receptacle ID and closes the receptacle if the receptacle contains packages (otherwise, deletes it). Used only by mailers using receptacles.
     */
    @WebResult(name = "CloseReceptacleResult", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
    @RequestWrapper(localName = "CloseReceptacle", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/", className = "com.winit.label.manager.impl.us.usps.intl.CloseReceptacle")
    @WebMethod(operationName = "CloseReceptacle", action = "http://www.usps-cpas.com/usps-cpas/GSSAPI/CloseReceptacle")
    @ResponseWrapper(localName = "CloseReceptacleResponse", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/", className = "com.winit.label.manager.impl.us.usps.intl.CloseReceptacleResponse")
    public com.winit.label.manager.impl.us.usps.intl.model.CommonResult closeReceptacle(
        @WebParam(name = "ReceptacleID", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
        java.lang.String receptacleID,
        @WebParam(name = "AccessToken", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
        java.lang.String accessToken
    );

    /**
     * Processes a labeled package at consolidator mailer location.
     */
    @WebResult(name = "ProcessLabeledPackageResult", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
    @RequestWrapper(localName = "ProcessLabeledPackage", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/", className = "com.winit.label.manager.impl.us.usps.intl.ProcessLabeledPackage")
    @WebMethod(operationName = "ProcessLabeledPackage", action = "http://www.usps-cpas.com/usps-cpas/GSSAPI/ProcessLabeledPackage")
    @ResponseWrapper(localName = "ProcessLabeledPackageResponse", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/", className = "com.winit.label.manager.impl.us.usps.intl.ProcessLabeledPackageResponse")
    public com.winit.label.manager.impl.us.usps.intl.model.CommonResult processLabeledPackage(
        @WebParam(name = "PackageID", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
        java.lang.String packageID,
        @WebParam(name = "MailingAgentID", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
        java.lang.String mailingAgentID,
        @WebParam(name = "BoxNumber", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
        int boxNumber,
        @WebParam(name = "AccessToken", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
        java.lang.String accessToken
    );

    /**
     * Processes a removed/re-entered or new package.
     */
    @WebResult(name = "ProcessThePackageResult", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
    @RequestWrapper(localName = "ProcessThePackage", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/", className = "com.winit.label.manager.impl.us.usps.intl.ProcessThePackage")
    @WebMethod(operationName = "ProcessThePackage", action = "http://www.usps-cpas.com/usps-cpas/GSSAPI/ProcessThePackage")
    @ResponseWrapper(localName = "ProcessThePackageResponse", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/", className = "com.winit.label.manager.impl.us.usps.intl.ProcessThePackageResponse")
    public com.winit.label.manager.impl.us.usps.intl.model.CommonResult processThePackage(
        @WebParam(name = "PackageID", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
        java.lang.String packageID,
        @WebParam(name = "MailingAgentID", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
        java.lang.String mailingAgentID,
        @WebParam(name = "BoxNumber", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
        int boxNumber,
        @WebParam(name = "AccessToken", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
        java.lang.String accessToken
    );

    /**
     * Retrieves the history of tracking events with the Postal Code for a package.
     */
    @WebResult(name = "TrackPackageWithPostalCodeResult", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
    @RequestWrapper(localName = "TrackPackageWithPostalCode", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/", className = "com.winit.label.manager.impl.us.usps.intl.TrackPackageWithPostalCode")
    @WebMethod(operationName = "TrackPackageWithPostalCode", action = "http://www.usps-cpas.com/usps-cpas/GSSAPI/TrackPackageWithPostalCode")
    @ResponseWrapper(localName = "TrackPackageWithPostalCodeResponse", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/", className = "com.winit.label.manager.impl.us.usps.intl.TrackPackageWithPostalCodeResponse")
    public com.winit.label.manager.impl.us.usps.intl.model.TrackingWithPostalCodeResult trackPackageWithPostalCode(
        @WebParam(name = "PackageID", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
        java.lang.String packageID,
        @WebParam(name = "MailingAgentID", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
        java.lang.String mailingAgentID,
        @WebParam(name = "BoxNumber", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
        int boxNumber,
        @WebParam(name = "AccessToken", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
        java.lang.String accessToken
    );

    /**
     * Uploads a package file to the GSS server.
     */
    @WebResult(name = "UploadPackageFileResult", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
    @RequestWrapper(localName = "UploadPackageFile", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/", className = "com.winit.label.manager.impl.us.usps.intl.UploadPackageFile")
    @WebMethod(operationName = "UploadPackageFile", action = "http://www.usps-cpas.com/usps-cpas/GSSAPI/UploadPackageFile")
    @ResponseWrapper(localName = "UploadPackageFileResponse", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/", className = "com.winit.label.manager.impl.us.usps.intl.UploadPackageFileResponse")
    public com.winit.label.manager.impl.us.usps.intl.model.CommonResult uploadPackageFile(
        @WebParam(name = "fileData", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
        byte[] fileData,
        @WebParam(name = "fileName", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
        java.lang.String fileName,
        @WebParam(name = "AccessToken", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
        java.lang.String accessToken
    );

    /**
     * Accepts package data from an originating mailer in the predefined XML format. Used by labeling locations only.
     */
    @WebResult(name = "LoadAndRecordLabeledPackageResult", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
    @RequestWrapper(localName = "LoadAndRecordLabeledPackage", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/", className = "com.winit.label.manager.impl.us.usps.intl.LoadAndRecordLabeledPackage")
    @WebMethod(operationName = "LoadAndRecordLabeledPackage", action = "http://www.usps-cpas.com/usps-cpas/GSSAPI/LoadAndRecordLabeledPackage")
    @ResponseWrapper(localName = "LoadAndRecordLabeledPackageResponse", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/", className = "com.winit.label.manager.impl.us.usps.intl.LoadAndRecordLabeledPackageResponse")
    public com.winit.label.manager.impl.us.usps.intl.model.LoadAndRecordLabeledPackageResponse.LoadAndRecordLabeledPackageResult loadAndRecordLabeledPackage(
        @WebParam(name = "xmlDoc", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
        com.winit.label.manager.impl.us.usps.intl.model.LoadAndRecordLabeledPackage.XmlDoc xmlDoc,
        @WebParam(name = "AccessToken", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
        java.lang.String accessToken
    );

    /**
     * This method is called first to consume GSS Mailer Web Services. Use the returned access token for each subsequent request.  The token has a session timeout of 20 minutes.
     */
    @WebResult(name = "AuthenticateUserResult", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
    @RequestWrapper(localName = "AuthenticateUser", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/", className = "com.winit.label.manager.impl.us.usps.intl.AuthenticateUser")
    @WebMethod(operationName = "AuthenticateUser", action = "http://www.usps-cpas.com/usps-cpas/GSSAPI/AuthenticateUser")
    @ResponseWrapper(localName = "AuthenticateUserResponse", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/", className = "com.winit.label.manager.impl.us.usps.intl.AuthenticateUserResponse")
    public com.winit.label.manager.impl.us.usps.intl.model.AuthenticateResult authenticateUser(
        @WebParam(name = "UserID", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
        java.lang.String userID,
        @WebParam(name = "Password", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
        java.lang.String password,
        @WebParam(name = "LocationID", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
        java.lang.String locationID,
        @WebParam(name = "WorkstationID", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
        java.lang.String workstationID
    );

    /**
     * Retrieves system status message.
     */
    @WebResult(name = "GetSystemStatusMessageResult", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
    @RequestWrapper(localName = "GetSystemStatusMessage", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/", className = "com.winit.label.manager.impl.us.usps.intl.GetSystemStatusMessage")
    @WebMethod(operationName = "GetSystemStatusMessage", action = "http://www.usps-cpas.com/usps-cpas/GSSAPI/GetSystemStatusMessage")
    @ResponseWrapper(localName = "GetSystemStatusMessageResponse", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/", className = "com.winit.label.manager.impl.us.usps.intl.GetSystemStatusMessageResponse")
    public com.winit.label.manager.impl.us.usps.intl.model.GetSystemStatusMessageResponse.GetSystemStatusMessageResult getSystemStatusMessage();

    /**
     * Generates Partial Dispatch Report
     */
    @WebResult(name = "GeneratePartialDispatchReportResult", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
    @RequestWrapper(localName = "GeneratePartialDispatchReport", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/", className = "com.winit.label.manager.impl.us.usps.intl.GeneratePartialDispatchReport")
    @WebMethod(operationName = "GeneratePartialDispatchReport", action = "http://www.usps-cpas.com/usps-cpas/GSSAPI/GeneratePartialDispatchReport")
    @ResponseWrapper(localName = "GeneratePartialDispatchReportResponse", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/", className = "com.winit.label.manager.impl.us.usps.intl.GeneratePartialDispatchReportResponse")
    public com.winit.label.manager.impl.us.usps.intl.model.GenerateReportResult generatePartialDispatchReport(
        @WebParam(name = "LocationID", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
        java.lang.String locationID,
        @WebParam(name = "AccessToken", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
        java.lang.String accessToken
    );

    /**
     * Retrieves customs label for a specified package ID processed up to 6 months.
     */
    @WebResult(name = "RegeneratePackageCustomsLabelResult", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
    @RequestWrapper(localName = "RegeneratePackageCustomsLabel", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/", className = "com.winit.label.manager.impl.us.usps.intl.RegeneratePackageCustomsLabel")
    @WebMethod(operationName = "RegeneratePackageCustomsLabel", action = "http://www.usps-cpas.com/usps-cpas/GSSAPI/RegeneratePackageCustomsLabel")
    @ResponseWrapper(localName = "RegeneratePackageCustomsLabelResponse", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/", className = "com.winit.label.manager.impl.us.usps.intl.RegeneratePackageCustomsLabelResponse")
    public com.winit.label.manager.impl.us.usps.intl.model.LabelResult regeneratePackageCustomsLabel(
        @WebParam(name = "PackageID", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
        java.lang.String packageID,
        @WebParam(name = "MailingAgentID", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
        java.lang.String mailingAgentID,
        @WebParam(name = "BoxNumber", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
        int boxNumber,
        @WebParam(name = "FileFormat", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
        java.lang.String fileFormat,
        @WebParam(name = "AccessToken", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
        java.lang.String accessToken
    );

    /**
     * Calculate Landed Cost
     */
    @WebResult(name = "CalculateLandedCostResult", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
    @RequestWrapper(localName = "CalculateLandedCost", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/", className = "com.winit.label.manager.impl.us.usps.intl.CalculateLandedCost")
    @WebMethod(operationName = "CalculateLandedCost", action = "http://www.usps-cpas.com/usps-cpas/GSSAPI/CalculateLandedCost")
    @ResponseWrapper(localName = "CalculateLandedCostResponse", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/", className = "com.winit.label.manager.impl.us.usps.intl.CalculateLandedCostResponse")
    public com.winit.label.manager.impl.us.usps.intl.model.CalculateLandedCostResponse.CalculateLandedCostResult calculateLandedCost(
        @WebParam(name = "CountryOfImport", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
        java.lang.String countryOfImport,
        @WebParam(name = "CountryOfExport", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
        java.lang.String countryOfExport,
        @WebParam(name = "ModeOfTransport", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
        java.lang.String modeOfTransport,
        @WebParam(name = "IncoTerm", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
        java.lang.String incoTerm,
        @WebParam(name = "TaxDetail", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
        java.lang.String taxDetail,
        @WebParam(name = "DateOfImport", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
        java.lang.String dateOfImport,
        @WebParam(name = "Items", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
        com.winit.label.manager.impl.us.usps.intl.model.CalculateLandedCost.Items items,
        @WebParam(name = "AccessToken", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
        java.lang.String accessToken
    );

    /**
     * Closes the frozen dispatch at the mailer�s location.
     */
    @WebResult(name = "CloseFrozenDispatchResult", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
    @RequestWrapper(localName = "CloseFrozenDispatch", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/", className = "com.winit.label.manager.impl.us.usps.intl.CloseFrozenDispatch")
    @WebMethod(operationName = "CloseFrozenDispatch", action = "http://www.usps-cpas.com/usps-cpas/GSSAPI/CloseFrozenDispatch")
    @ResponseWrapper(localName = "CloseFrozenDispatchResponse", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/", className = "com.winit.label.manager.impl.us.usps.intl.CloseFrozenDispatchResponse")
    public com.winit.label.manager.impl.us.usps.intl.model.CloseDispatchResult closeFrozenDispatch(
        @WebParam(name = "FreezeDispatchID", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
        java.lang.String freezeDispatchID,
        @WebParam(name = "VehicleNum", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
        java.lang.String vehicleNum,
        @WebParam(name = "VehicleType", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
        java.lang.String vehicleType,
        @WebParam(name = "DepDateTime", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
        java.lang.String depDateTime,
        @WebParam(name = "ArrDateTime", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
        java.lang.String arrDateTime,
        @WebParam(name = "AccessToken", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
        java.lang.String accessToken
    );

    /**
     * Opens a receptacle for a destination location. Used only by mailers using receptacles.
     */
    @WebResult(name = "OpenReceptacleResult", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
    @RequestWrapper(localName = "OpenReceptacle", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/", className = "com.winit.label.manager.impl.us.usps.intl.OpenReceptacle")
    @WebMethod(operationName = "OpenReceptacle", action = "http://www.usps-cpas.com/usps-cpas/GSSAPI/OpenReceptacle")
    @ResponseWrapper(localName = "OpenReceptacleResponse", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/", className = "com.winit.label.manager.impl.us.usps.intl.OpenReceptacleResponse")
    public com.winit.label.manager.impl.us.usps.intl.model.CommonResult openReceptacle(
        @WebParam(name = "DestinationLocationID", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
        java.lang.String destinationLocationID,
        @WebParam(name = "AccessToken", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
        java.lang.String accessToken
    );

    /**
     * Returns a list of commodity names used for GXG.
     */
    @WebResult(name = "GetGXGCommodityInfoResult", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
    @RequestWrapper(localName = "GetGXGCommodityInfo", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/", className = "com.winit.label.manager.impl.us.usps.intl.GetGXGCommodityInfo")
    @WebMethod(operationName = "GetGXGCommodityInfo", action = "http://www.usps-cpas.com/usps-cpas/GSSAPI/GetGXGCommodityInfo")
    @ResponseWrapper(localName = "GetGXGCommodityInfoResponse", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/", className = "com.winit.label.manager.impl.us.usps.intl.GetGXGCommodityInfoResponse")
    public com.winit.label.manager.impl.us.usps.intl.model.GXGCommodityInfoResult getGXGCommodityInfo(
        @WebParam(name = "AccessToken", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
        java.lang.String accessToken
    );

    /**
     * Closes the open dispatch at the mailer�s location.
     */
    @WebResult(name = "CloseDispatchResult", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
    @RequestWrapper(localName = "CloseDispatch", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/", className = "com.winit.label.manager.impl.us.usps.intl.CloseDispatch")
    @WebMethod(operationName = "CloseDispatch", action = "http://www.usps-cpas.com/usps-cpas/GSSAPI/CloseDispatch")
    @ResponseWrapper(localName = "CloseDispatchResponse", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/", className = "com.winit.label.manager.impl.us.usps.intl.CloseDispatchResponse")
    public com.winit.label.manager.impl.us.usps.intl.model.CloseDispatchResult closeDispatch(
        @WebParam(name = "VehicleNum", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
        java.lang.String vehicleNum,
        @WebParam(name = "VehicleType", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
        java.lang.String vehicleType,
        @WebParam(name = "DepDateTime", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
        java.lang.String depDateTime,
        @WebParam(name = "ArrDateTime", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
        java.lang.String arrDateTime,
        @WebParam(name = "AccessToken", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
        java.lang.String accessToken
    );

    /**
     * Closes the dispatch to the destination location.
     */
    @WebResult(name = "CloseDispatchToDestinationLocationResult", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
    @RequestWrapper(localName = "CloseDispatchToDestinationLocation", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/", className = "com.winit.label.manager.impl.us.usps.intl.CloseDispatchToDestinationLocation")
    @WebMethod(operationName = "CloseDispatchToDestinationLocation", action = "http://www.usps-cpas.com/usps-cpas/GSSAPI/CloseDispatchToDestinationLocation")
    @ResponseWrapper(localName = "CloseDispatchToDestinationLocationResponse", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/", className = "com.winit.label.manager.impl.us.usps.intl.CloseDispatchToDestinationLocationResponse")
    public com.winit.label.manager.impl.us.usps.intl.model.CloseDispatchResult closeDispatchToDestinationLocation(
        @WebParam(name = "DestinationLocationID", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
        java.lang.String destinationLocationID,
        @WebParam(name = "VehicleNum", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
        java.lang.String vehicleNum,
        @WebParam(name = "VehicleType", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
        java.lang.String vehicleType,
        @WebParam(name = "DepDateTime", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
        java.lang.String depDateTime,
        @WebParam(name = "ArrDateTime", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
        java.lang.String arrDateTime,
        @WebParam(name = "AccessToken", targetNamespace = "http://www.usps-cpas.com/usps-cpas/GSSAPI/")
        java.lang.String accessToken
    );
}
