//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.16 at 02:20:16 ���� CST 
//


package com.winit.label.manager.impl.us.usps.intl.model.ext.response;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.lable.usa.usps.model.ext.response package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Manifest_QNAME = new QName("mailerdataformatf06.xsd", "Manifest");
    private final static QName _PackageIdentifier_QNAME = new QName("mailerdataformatf06.xsd", "Package_Identifier");
    private final static QName _PackageHold_QNAME = new QName("mailerdataformatf06.xsd", "Package_Hold");
    private final static QName _PackageMessage_QNAME = new QName("mailerdataformatf06.xsd", "Package_Message");
    private final static QName _Package_QNAME = new QName("mailerdataformatf06.xsd", "Package");
    private final static QName _PackageWarning_QNAME = new QName("mailerdataformatf06.xsd", "Package_Warning");
    private final static QName _DispatchConfirmation_QNAME = new QName("mailerdataformatf06.xsd", "Dispatch_Confirmation");
    private final static QName _PackageError_QNAME = new QName("mailerdataformatf06.xsd", "Package_Error");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.lable.usa.usps.model.ext.response
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ResponseManifest }
     * 
     */
    public ResponseManifest createResponseManifest() {
        return new ResponseManifest();
    }

    /**
     * Create an instance of {@link DispatchConfirmation }
     * 
     */
    public DispatchConfirmation createDispatchConfirmation() {
        return new DispatchConfirmation();
    }

    /**
     * Create an instance of {@link PackageHold }
     * 
     */
    public PackageHold createPackageHold() {
        return new PackageHold();
    }

    /**
     * Create an instance of {@link PackageMessage }
     * 
     */
    public PackageMessage createPackageMessage() {
        return new PackageMessage();
    }

    /**
     * Create an instance of {@link PackageError }
     * 
     */
    public PackageError createPackageError() {
        return new PackageError();
    }

    /**
     * Create an instance of {@link Package }
     * 
     */
    public Package createPackage() {
        return new Package();
    }

    /**
     * Create an instance of {@link PackageIdentifier }
     * 
     */
    public PackageIdentifier createPackageIdentifier() {
        return new PackageIdentifier();
    }

    /**
     * Create an instance of {@link PackageWarning }
     * 
     */
    public PackageWarning createPackageWarning() {
        return new PackageWarning();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ResponseManifest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "mailerdataformatf06.xsd", name = "Manifest")
    public JAXBElement<ResponseManifest> createManifest(ResponseManifest value) {
        return new JAXBElement<ResponseManifest>(_Manifest_QNAME, ResponseManifest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PackageIdentifier }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "mailerdataformatf06.xsd", name = "Package_Identifier")
    public JAXBElement<PackageIdentifier> createPackageIdentifier(PackageIdentifier value) {
        return new JAXBElement<PackageIdentifier>(_PackageIdentifier_QNAME, PackageIdentifier.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PackageHold }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "mailerdataformatf06.xsd", name = "Package_Hold")
    public JAXBElement<PackageHold> createPackageHold(PackageHold value) {
        return new JAXBElement<PackageHold>(_PackageHold_QNAME, PackageHold.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PackageMessage }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "mailerdataformatf06.xsd", name = "Package_Message")
    public JAXBElement<PackageMessage> createPackageMessage(PackageMessage value) {
        return new JAXBElement<PackageMessage>(_PackageMessage_QNAME, PackageMessage.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Package }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "mailerdataformatf06.xsd", name = "Package")
    public JAXBElement<Package> createPackage(Package value) {
        return new JAXBElement<Package>(_Package_QNAME, Package.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PackageWarning }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "mailerdataformatf06.xsd", name = "Package_Warning")
    public JAXBElement<PackageWarning> createPackageWarning(PackageWarning value) {
        return new JAXBElement<PackageWarning>(_PackageWarning_QNAME, PackageWarning.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DispatchConfirmation }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "mailerdataformatf06.xsd", name = "Dispatch_Confirmation")
    public JAXBElement<DispatchConfirmation> createDispatchConfirmation(DispatchConfirmation value) {
        return new JAXBElement<DispatchConfirmation>(_DispatchConfirmation_QNAME, DispatchConfirmation.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PackageError }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "mailerdataformatf06.xsd", name = "Package_Error")
    public JAXBElement<PackageError> createPackageError(PackageError value) {
        return new JAXBElement<PackageError>(_PackageError_QNAME, PackageError.class, null, value);
    }

}
