//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.15 at 12:41:46 ���� CST 
//


package com.winit.label.manager.impl.us.usps.intl.model.ext.response;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlMixed;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Manifest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Manifest">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{mailerdataformatf06.xsd}Dispatch_Confirmation"/>
 *         &lt;any maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="PackageID" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Manifest", propOrder = {
    "dispatchConfirmation",
    "any"
})
@XmlRootElement
public class ResponseManifest {

    @XmlElement(name = "Dispatch_Confirmation", required = true)
    protected DispatchConfirmation dispatchConfirmation;
    @XmlMixed
    @XmlAnyElement(lax = true)
    protected List<Object> any;
    @XmlAttribute(name = "PackageID")
    protected String packageID;

    /**
     * Gets the value of the dispatchConfirmation property.
     * 
     * @return
     *     possible object is
     *     {@link DispatchConfirmation }
     *     
     */
    public DispatchConfirmation getDispatchConfirmation() {
        return dispatchConfirmation;
    }

    /**
     * Sets the value of the dispatchConfirmation property.
     * 
     * @param value
     *     allowed object is
     *     {@link DispatchConfirmation }
     *     
     */
    public void setDispatchConfirmation(DispatchConfirmation value) {
        this.dispatchConfirmation = value;
    }

    /**
     * Gets the value of the any property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the any property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAny().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Object }
     * 
     * 
     */
    public List<Object> getAny() {
        if (any == null) {
            any = new ArrayList<Object>();
        }
        return this.any;
    }

    /**
     * Gets the value of the packageID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPackageID() {
        return packageID;
    }

    /**
     * Sets the value of the packageID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPackageID(String value) {
        this.packageID = value;
    }
    
    public List<Package> getPackages(){
    	return getContentInAny(Package.class);
    }
    public List<PackageHold> getPackageHolds(){
    	return getContentInAny(PackageHold.class);
    }
    public List<PackageError> getPackageErrors(){
    	return getContentInAny(PackageError.class);
    }
    public List<PackageWarning> getPackageWarnings(){
    	return getContentInAny(PackageWarning.class);
    }
    
    public <T> List<T> getContentInAny(Class<T> clazz){
    	List<T> pkgs = new ArrayList<T>();
    	for(Object it:this.getAny()){
			if(it instanceof JAXBElement<?>){
				JAXBElement je = (JAXBElement) it;
				if(je.getValue().getClass().equals(clazz)){
					T p = (T)je.getValue();
					pkgs.add(p);
				}
			}
		}
    	return pkgs;
    }
}
