//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.03 at 10:27:01 ���� CST 
//


package com.winit.label.manager.impl.gb.dpd.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for trackingresponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="trackingresponse">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="trackingdetails" type="{http://www.example.org/trackingresponse}trackingdetails"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlRootElement(name="trackingresponse")
public class Trackingresponse {

    @XmlElement(required = true)
    protected Trackingdetails trackingdetails;
    
    protected String error;

    /**
     * Gets the value of the trackingdetails property.
     * 
     * @return
     *     possible object is
     *     {@link Trackingdetails }
     *     
     */
    public Trackingdetails getTrackingdetails() {
        return trackingdetails;
    }

    /**
     * Sets the value of the trackingdetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link Trackingdetails }
     *     
     */
    public void setTrackingdetails(Trackingdetails value) {
        this.trackingdetails = value;
    }
    
    public String getError() {
        return error;
    }

    public void setError(String value) {
        this.error = value;
    }

}
