//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.21 at 03:30:12 ���� CST 
//


package com.winit.label.manager.impl.de.dpd.shipment;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Bundles hazardous materials data.
 * 
 * <p>Java class for hazardous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="hazardous">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="identificationUnNo">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;length value="4"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="identificationClass">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="6"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="classificationCode" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="5"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="packingGroup" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="5"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="packingCode">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="0A"/>
 *               &lt;enumeration value="0A1"/>
 *               &lt;enumeration value="0A2"/>
 *               &lt;enumeration value="1A"/>
 *               &lt;enumeration value="1A1"/>
 *               &lt;enumeration value="1A2"/>
 *               &lt;enumeration value="1B"/>
 *               &lt;enumeration value="1B1"/>
 *               &lt;enumeration value="1B2"/>
 *               &lt;enumeration value="1H"/>
 *               &lt;enumeration value="1H1"/>
 *               &lt;enumeration value="1H2"/>
 *               &lt;enumeration value="3A"/>
 *               &lt;enumeration value="3A1"/>
 *               &lt;enumeration value="3A2"/>
 *               &lt;enumeration value="3B"/>
 *               &lt;enumeration value="3B1"/>
 *               &lt;enumeration value="3B2"/>
 *               &lt;enumeration value="3H"/>
 *               &lt;enumeration value="3H1"/>
 *               &lt;enumeration value="3H2"/>
 *               &lt;enumeration value="4A"/>
 *               &lt;enumeration value="4B"/>
 *               &lt;enumeration value="4D"/>
 *               &lt;enumeration value="4G"/>
 *               &lt;enumeration value="4H"/>
 *               &lt;enumeration value="4H1"/>
 *               &lt;enumeration value="4H2"/>
 *               &lt;enumeration value="5H"/>
 *               &lt;enumeration value="5M"/>
 *               &lt;enumeration value="6H"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="description">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="160"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="subsidiaryRisk" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="10"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="tunnelRestrictionCode" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="A"/>
 *               &lt;enumeration value="B"/>
 *               &lt;enumeration value="C"/>
 *               &lt;enumeration value="D"/>
 *               &lt;enumeration value="E"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="hazardousWeight">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;fractionDigits value="2"/>
 *               &lt;totalDigits value="6"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="netWeight" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *               &lt;fractionDigits value="2"/>
 *               &lt;totalDigits value="6"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="factor">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *               &lt;maxInclusive value="999"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="notOtherwiseSpecified" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="150"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "hazardous", propOrder = {
    "identificationUnNo",
    "identificationClass",
    "classificationCode",
    "packingGroup",
    "packingCode",
    "description",
    "subsidiaryRisk",
    "tunnelRestrictionCode",
    "hazardousWeight",
    "netWeight",
    "factor",
    "notOtherwiseSpecified"
})
public class Hazardous {

    @XmlElement(required = true)
    protected String identificationUnNo;
    @XmlElement(required = true)
    protected String identificationClass;
    protected String classificationCode;
    protected String packingGroup;
    @XmlElement(required = true)
    protected String packingCode;
    @XmlElement(required = true)
    protected String description;
    protected String subsidiaryRisk;
    protected String tunnelRestrictionCode;
    @XmlElement(required = true)
    protected BigDecimal hazardousWeight;
    protected BigDecimal netWeight;
    protected int factor;
    protected String notOtherwiseSpecified;

    /**
     * Gets the value of the identificationUnNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdentificationUnNo() {
        return identificationUnNo;
    }

    /**
     * Sets the value of the identificationUnNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdentificationUnNo(String value) {
        this.identificationUnNo = value;
    }

    /**
     * Gets the value of the identificationClass property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdentificationClass() {
        return identificationClass;
    }

    /**
     * Sets the value of the identificationClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdentificationClass(String value) {
        this.identificationClass = value;
    }

    /**
     * Gets the value of the classificationCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClassificationCode() {
        return classificationCode;
    }

    /**
     * Sets the value of the classificationCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClassificationCode(String value) {
        this.classificationCode = value;
    }

    /**
     * Gets the value of the packingGroup property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPackingGroup() {
        return packingGroup;
    }

    /**
     * Sets the value of the packingGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPackingGroup(String value) {
        this.packingGroup = value;
    }

    /**
     * Gets the value of the packingCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPackingCode() {
        return packingCode;
    }

    /**
     * Sets the value of the packingCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPackingCode(String value) {
        this.packingCode = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the subsidiaryRisk property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubsidiaryRisk() {
        return subsidiaryRisk;
    }

    /**
     * Sets the value of the subsidiaryRisk property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubsidiaryRisk(String value) {
        this.subsidiaryRisk = value;
    }

    /**
     * Gets the value of the tunnelRestrictionCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTunnelRestrictionCode() {
        return tunnelRestrictionCode;
    }

    /**
     * Sets the value of the tunnelRestrictionCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTunnelRestrictionCode(String value) {
        this.tunnelRestrictionCode = value;
    }

    /**
     * Gets the value of the hazardousWeight property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getHazardousWeight() {
        return hazardousWeight;
    }

    /**
     * Sets the value of the hazardousWeight property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setHazardousWeight(BigDecimal value) {
        this.hazardousWeight = value;
    }

    /**
     * Gets the value of the netWeight property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getNetWeight() {
        return netWeight;
    }

    /**
     * Sets the value of the netWeight property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setNetWeight(BigDecimal value) {
        this.netWeight = value;
    }

    /**
     * Gets the value of the factor property.
     * 
     */
    public int getFactor() {
        return factor;
    }

    /**
     * Sets the value of the factor property.
     * 
     */
    public void setFactor(int value) {
        this.factor = value;
    }

    /**
     * Gets the value of the notOtherwiseSpecified property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNotOtherwiseSpecified() {
        return notOtherwiseSpecified;
    }

    /**
     * Sets the value of the notOtherwiseSpecified property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNotOtherwiseSpecified(String value) {
        this.notOtherwiseSpecified = value;
    }

}
