//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.21 at 03:30:12 ���� CST 
//


package com.winit.label.manager.impl.de.dpd.shipment;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.lable.germany.dpd package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _StoreOrdersResponse_QNAME = new QName("http://dpd.com/common/service/types/ShipmentService/2.0", "storeOrdersResponse");
    private final static QName _StoreOrders_QNAME = new QName("http://dpd.com/common/service/types/ShipmentService/2.0", "storeOrders");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.lable.germany.dpd
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ParcelInformationType }
     * 
     */
    public ParcelInformationType createParcelInformationType() {
        return new ParcelInformationType();
    }

    /**
     * Create an instance of {@link StoreOrdersResponseType }
     * 
     */
    public StoreOrdersResponseType createStoreOrdersResponseType() {
        return new StoreOrdersResponseType();
    }

    /**
     * Create an instance of {@link ProductAndServiceData }
     * 
     */
    public ProductAndServiceData createProductAndServiceData() {
        return new ProductAndServiceData();
    }

    /**
     * Create an instance of {@link ProactiveNotification }
     * 
     */
    public ProactiveNotification createProactiveNotification() {
        return new ProactiveNotification();
    }

    /**
     * Create an instance of {@link International }
     * 
     */
    public International createInternational() {
        return new International();
    }

    /**
     * Create an instance of {@link StoreOrdersResponse }
     * 
     */
    public StoreOrdersResponse createStoreOrdersResponse() {
        return new StoreOrdersResponse();
    }

    /**
     * Create an instance of {@link GeneralShipmentData }
     * 
     */
    public GeneralShipmentData createGeneralShipmentData() {
        return new GeneralShipmentData();
    }

    /**
     * Create an instance of {@link FaultCodeType }
     * 
     */
    public FaultCodeType createFaultCodeType() {
        return new FaultCodeType();
    }

    /**
     * Create an instance of {@link Delivery }
     * 
     */
    public Delivery createDelivery() {
        return new Delivery();
    }

    /**
     * Create an instance of {@link StoreOrders }
     * 
     */
    public StoreOrders createStoreOrders() {
        return new StoreOrders();
    }

    /**
     * Create an instance of {@link Hazardous }
     * 
     */
    public Hazardous createHazardous() {
        return new Hazardous();
    }

    /**
     * Create an instance of {@link Address }
     * 
     */
    public Address createAddress() {
        return new Address();
    }

    /**
     * Create an instance of {@link Pickup }
     * 
     */
    public Pickup createPickup() {
        return new Pickup();
    }

    /**
     * Create an instance of {@link Notification }
     * 
     */
    public Notification createNotification() {
        return new Notification();
    }

    /**
     * Create an instance of {@link ShipmentResponse }
     * 
     */
    public ShipmentResponse createShipmentResponse() {
        return new ShipmentResponse();
    }

    /**
     * Create an instance of {@link PersonalDelivery }
     * 
     */
    public PersonalDelivery createPersonalDelivery() {
        return new PersonalDelivery();
    }

    /**
     * Create an instance of {@link ShipmentServiceData }
     * 
     */
    public ShipmentServiceData createShipmentServiceData() {
        return new ShipmentServiceData();
    }

    /**
     * Create an instance of {@link ParcelShopDelivery }
     * 
     */
    public ParcelShopDelivery createParcelShopDelivery() {
        return new ParcelShopDelivery();
    }

    /**
     * Create an instance of {@link Cod }
     * 
     */
    public Cod createCod() {
        return new Cod();
    }

    /**
     * Create an instance of {@link Parcel }
     * 
     */
    public Parcel createParcel() {
        return new Parcel();
    }

    /**
     * Create an instance of {@link HigherInsurance }
     * 
     */
    public HigherInsurance createHigherInsurance() {
        return new HigherInsurance();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StoreOrdersResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://dpd.com/common/service/types/ShipmentService/2.0", name = "storeOrdersResponse")
    public JAXBElement<StoreOrdersResponse> createStoreOrdersResponse(StoreOrdersResponse value) {
        return new JAXBElement<StoreOrdersResponse>(_StoreOrdersResponse_QNAME, StoreOrdersResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StoreOrders }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://dpd.com/common/service/types/ShipmentService/2.0", name = "storeOrders")
    public JAXBElement<StoreOrders> createStoreOrders(StoreOrders value) {
        return new JAXBElement<StoreOrders>(_StoreOrders_QNAME, StoreOrders.class, null, value);
    }

}
