//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.21 at 03:30:12 ���� CST 
//


package com.winit.label.manager.impl.de.dpd.shipment;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for storeOrdersResponseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="storeOrdersResponseType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="parcellabelsPDF" type="{http://www.w3.org/2001/XMLSchema}base64Binary" minOccurs="0"/>
 *         &lt;element name="shipmentResponses" type="{http://dpd.com/common/service/types/ShipmentService/2.0}shipmentResponse" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "storeOrdersResponseType", propOrder = {
    "parcellabelsPDF",
    "shipmentResponses"
})
public class StoreOrdersResponseType {

    protected byte[] parcellabelsPDF;
    protected List<ShipmentResponse> shipmentResponses;

    /**
     * Gets the value of the parcellabelsPDF property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getParcellabelsPDF() {
        return parcellabelsPDF;
    }

    /**
     * Sets the value of the parcellabelsPDF property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setParcellabelsPDF(byte[] value) {
        this.parcellabelsPDF = ((byte[]) value);
    }

    /**
     * Gets the value of the shipmentResponses property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the shipmentResponses property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getShipmentResponses().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ShipmentResponse }
     * 
     * 
     */
    public List<ShipmentResponse> getShipmentResponses() {
        if (shipmentResponses == null) {
            shipmentResponses = new ArrayList<ShipmentResponse>();
        }
        return this.shipmentResponses;
    }

}
