//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.04 at 03:48:22 ���� CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.dhl.com/pickupdatatypes_global")
package com.winit.label.manager.impl.us.dhl.model.pickupdatatypes_global;
