//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.04 at 03:48:22 ���� CST 
//


package com.winit.label.manager.impl.us.dhl.model.pickupdatatypes_global;

import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;

import com.winit.label.manager.impl.us.dhl.model.datatypes_global.DimensionUnit;
import com.winit.label.manager.impl.us.dhl.model.datatypes_global.ProductCode;
import com.winit.label.manager.impl.us.dhl.model.datatypes_global.WeightUnit;


/**
 * <p>Java class for ShipmentDetails complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ShipmentDetails">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AccountType" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *               &lt;maxLength value="1"/>
 *               &lt;enumeration value="D"/>
 *               &lt;enumeration value="C"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="AccountNumber" type="{http://www.dhl.com/datatypes_global}AccountNumber" minOccurs="0"/>
 *         &lt;element name="ChargeCard" type="{http://www.dhl.com/pickupdatatypes_global}ChargeCard" minOccurs="0"/>
 *         &lt;element name="BillToAccountNumber" type="{http://www.dhl.com/datatypes_global}AccountNumber" minOccurs="0"/>
 *         &lt;element name="AWBNumber" type="{http://www.dhl.com/datatypes_global}AWBNumber" minOccurs="0"/>
 *         &lt;element name="NumberOfPieces" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" minOccurs="0"/>
 *         &lt;element name="Weight" type="{http://www.dhl.com/datatypes_global}Weight"/>
 *         &lt;element name="WeightUnit" type="{http://www.dhl.com/datatypes_global}WeightUnit"/>
 *         &lt;element name="GlobalProductCode" type="{http://www.dhl.com/datatypes_global}ProductCode" minOccurs="0"/>
 *         &lt;element name="DoorTo" type="{http://www.dhl.com/pickupdatatypes_global}DoorTo"/>
 *         &lt;element name="DimensionUnit" type="{http://www.dhl.com/datatypes_global}DimensionUnit" minOccurs="0"/>
 *         &lt;element name="InsuredAmount" type="{http://www.dhl.com/datatypes_global}Money" minOccurs="0"/>
 *         &lt;element name="InsuredCurrencyCode" type="{http://www.dhl.com/datatypes_global}CurrencyCode" minOccurs="0"/>
 *         &lt;element name="Pieces" type="{http://www.dhl.com/pickupdatatypes_global}Piece" minOccurs="0"/>
 *         &lt;element name="SpecialService" type="{http://www.dhl.com/datatypes_global}SpecialServiceType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ShipmentDetails", propOrder = {
    "accountType",
    "accountNumber",
    "chargeCard",
    "billToAccountNumber",
    "awbNumber",
    "numberOfPieces",
    "weight",
    "weightUnit",
    "globalProductCode",
    "doorTo",
    "dimensionUnit",
    "insuredAmount",
    "insuredCurrencyCode",
    "pieces",
    "specialService"
})
public class ShipmentDetails {

    @XmlElement(name = "AccountType")
    protected String accountType;
    @XmlElement(name = "AccountNumber")
    protected String accountNumber;
    @XmlElement(name = "ChargeCard")
    protected ChargeCard chargeCard;
    @XmlElement(name = "BillToAccountNumber")
    protected String billToAccountNumber;
    @XmlElement(name = "AWBNumber")
    protected String awbNumber;
    @XmlElement(name = "NumberOfPieces")
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger numberOfPieces;
    @XmlElement(name = "Weight", required = true)
    protected BigDecimal weight;
    @XmlElement(name = "WeightUnit", required = true)
    protected WeightUnit weightUnit;
    @XmlElement(name = "GlobalProductCode")
    protected ProductCode globalProductCode;
    @XmlElement(name = "DoorTo", required = true)
    protected DoorTo doorTo;
    @XmlElement(name = "DimensionUnit")
    protected DimensionUnit dimensionUnit;
    @XmlElement(name = "InsuredAmount")
    protected Float insuredAmount;
    @XmlElement(name = "InsuredCurrencyCode")
    protected String insuredCurrencyCode;
    @XmlElement(name = "Pieces")
    protected Piece pieces;
    @XmlElement(name = "SpecialService")
    protected List<String> specialService;

    /**
     * Gets the value of the accountType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountType() {
        return accountType;
    }

    /**
     * Sets the value of the accountType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountType(String value) {
        this.accountType = value;
    }

    /**
     * Gets the value of the accountNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountNumber() {
        return accountNumber;
    }

    /**
     * Sets the value of the accountNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountNumber(String value) {
        this.accountNumber = value;
    }

    /**
     * Gets the value of the chargeCard property.
     * 
     * @return
     *     possible object is
     *     {@link ChargeCard }
     *     
     */
    public ChargeCard getChargeCard() {
        return chargeCard;
    }

    /**
     * Sets the value of the chargeCard property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChargeCard }
     *     
     */
    public void setChargeCard(ChargeCard value) {
        this.chargeCard = value;
    }

    /**
     * Gets the value of the billToAccountNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBillToAccountNumber() {
        return billToAccountNumber;
    }

    /**
     * Sets the value of the billToAccountNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBillToAccountNumber(String value) {
        this.billToAccountNumber = value;
    }

    /**
     * Gets the value of the awbNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAWBNumber() {
        return awbNumber;
    }

    /**
     * Sets the value of the awbNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAWBNumber(String value) {
        this.awbNumber = value;
    }

    /**
     * Gets the value of the numberOfPieces property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumberOfPieces() {
        return numberOfPieces;
    }

    /**
     * Sets the value of the numberOfPieces property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumberOfPieces(BigInteger value) {
        this.numberOfPieces = value;
    }

    /**
     * Gets the value of the weight property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getWeight() {
        return weight;
    }

    /**
     * Sets the value of the weight property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setWeight(BigDecimal value) {
        this.weight = value;
    }

    /**
     * Gets the value of the weightUnit property.
     * 
     * @return
     *     possible object is
     *     {@link WeightUnit }
     *     
     */
    public WeightUnit getWeightUnit() {
        return weightUnit;
    }

    /**
     * Sets the value of the weightUnit property.
     * 
     * @param value
     *     allowed object is
     *     {@link WeightUnit }
     *     
     */
    public void setWeightUnit(WeightUnit value) {
        this.weightUnit = value;
    }

    /**
     * Gets the value of the globalProductCode property.
     * 
     * @return
     *     possible object is
     *     {@link ProductCode }
     *     
     */
    public ProductCode getGlobalProductCode() {
        return globalProductCode;
    }

    /**
     * Sets the value of the globalProductCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProductCode }
     *     
     */
    public void setGlobalProductCode(ProductCode value) {
        this.globalProductCode = value;
    }

    /**
     * Gets the value of the doorTo property.
     * 
     * @return
     *     possible object is
     *     {@link DoorTo }
     *     
     */
    public DoorTo getDoorTo() {
        return doorTo;
    }

    /**
     * Sets the value of the doorTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link DoorTo }
     *     
     */
    public void setDoorTo(DoorTo value) {
        this.doorTo = value;
    }

    /**
     * Gets the value of the dimensionUnit property.
     * 
     * @return
     *     possible object is
     *     {@link DimensionUnit }
     *     
     */
    public DimensionUnit getDimensionUnit() {
        return dimensionUnit;
    }

    /**
     * Sets the value of the dimensionUnit property.
     * 
     * @param value
     *     allowed object is
     *     {@link DimensionUnit }
     *     
     */
    public void setDimensionUnit(DimensionUnit value) {
        this.dimensionUnit = value;
    }

    /**
     * Gets the value of the insuredAmount property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getInsuredAmount() {
        return insuredAmount;
    }

    /**
     * Sets the value of the insuredAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setInsuredAmount(Float value) {
        this.insuredAmount = value;
    }

    /**
     * Gets the value of the insuredCurrencyCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInsuredCurrencyCode() {
        return insuredCurrencyCode;
    }

    /**
     * Sets the value of the insuredCurrencyCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInsuredCurrencyCode(String value) {
        this.insuredCurrencyCode = value;
    }

    /**
     * Gets the value of the pieces property.
     * 
     * @return
     *     possible object is
     *     {@link Piece }
     *     
     */
    public Piece getPieces() {
        return pieces;
    }

    /**
     * Sets the value of the pieces property.
     * 
     * @param value
     *     allowed object is
     *     {@link Piece }
     *     
     */
    public void setPieces(Piece value) {
        this.pieces = value;
    }

    /**
     * Gets the value of the specialService property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the specialService property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSpecialService().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getSpecialService() {
        if (specialService == null) {
            specialService = new ArrayList<String>();
        }
        return this.specialService;
    }

}
