//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.16 at 02:20:16 ���� CST 
//


package com.winit.label.manager.impl.us.usps.intl.model.ext.response;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DispatchConfirmation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DispatchConfirmation">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DispatchID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Reject_Package_Count" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="Version_Number" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DispatchConfirmation", propOrder = {
    "dispatchID",
    "rejectPackageCount",
    "versionNumber"
})
public class DispatchConfirmation {

    @XmlElement(name = "DispatchID", required = true)
    protected String dispatchID;
    @XmlElement(name = "Reject_Package_Count")
    protected int rejectPackageCount;
    @XmlElement(name = "Version_Number", required = true)
    protected String versionNumber;

    /**
     * Gets the value of the dispatchID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDispatchID() {
        return dispatchID;
    }

    /**
     * Sets the value of the dispatchID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDispatchID(String value) {
        this.dispatchID = value;
    }

    /**
     * Gets the value of the rejectPackageCount property.
     * 
     */
    public int getRejectPackageCount() {
        return rejectPackageCount;
    }

    /**
     * Sets the value of the rejectPackageCount property.
     * 
     */
    public void setRejectPackageCount(int value) {
        this.rejectPackageCount = value;
    }

    /**
     * Gets the value of the versionNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersionNumber() {
        return versionNumber;
    }

    /**
     * Sets the value of the versionNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersionNumber(String value) {
        this.versionNumber = value;
    }

}
