//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.22 at 02:30:45 ���� CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://dpd.com/common/service/types/Authentication/2.0")
package com.winit.label.manager.impl.de.dpd.login.response;
