//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.04 at 03:48:22 ���� CST 
//


package com.winit.label.manager.impl.us.dhl.model;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.dhl package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.dhl
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ShipmentResponse }
     * 
     */
    public ShipmentResponse createShipmentResponse() {
        return new ShipmentResponse();
    }

    /**
     * Create an instance of {@link ModifyPUResponse }
     * 
     */
    public ModifyPUResponse createModifyPUResponse() {
        return new ModifyPUResponse();
    }

    /**
     * Create an instance of {@link ShipmentRequest }
     * 
     */
    public ShipmentRequest createShipmentRequest() {
        return new ShipmentRequest();
    }

    /**
     * Create an instance of {@link UnknownTrackingRequest }
     * 
     */
    public UnknownTrackingRequest createUnknownTrackingRequest() {
        return new UnknownTrackingRequest();
    }

    /**
     * Create an instance of {@link ModifyPURequest }
     * 
     */
    public ModifyPURequest createModifyPURequest() {
        return new ModifyPURequest();
    }

    /**
     * Create an instance of {@link ErrorResponse }
     * 
     */
    public ErrorResponse createErrorResponse() {
        return new ErrorResponse();
    }

    /**
     * Create an instance of {@link RouteResponse }
     * 
     */
    public RouteResponse createRouteResponse() {
        return new RouteResponse();
    }

    /**
     * Create an instance of {@link ShipmentResponse.Barcodes }
     * 
     */
    public ShipmentResponse.Barcodes createShipmentResponseBarcodes() {
        return new ShipmentResponse.Barcodes();
    }

    /**
     * Create an instance of {@link RouteRequest }
     * 
     */
    public RouteRequest createRouteRequest() {
        return new RouteRequest();
    }

    /**
     * Create an instance of {@link ShipmentValidateErrorResponse }
     * 
     */
    public ShipmentValidateErrorResponse createShipmentValidateErrorResponse() {
        return new ShipmentValidateErrorResponse();
    }

    /**
     * Create an instance of {@link CancelPUResponse }
     * 
     */
    public CancelPUResponse createCancelPUResponse() {
        return new CancelPUResponse();
    }

    /**
     * Create an instance of {@link TrackingResponse }
     * 
     */
    public TrackingResponse createTrackingResponse() {
        return new TrackingResponse();
    }

    /**
     * Create an instance of {@link BookPURequest }
     * 
     */
    public BookPURequest createBookPURequest() {
        return new BookPURequest();
    }

    /**
     * Create an instance of {@link KnownTrackingRequest }
     * 
     */
    public KnownTrackingRequest createKnownTrackingRequest() {
        return new KnownTrackingRequest();
    }

    /**
     * Create an instance of {@link CancelPURequest }
     * 
     */
    public CancelPURequest createCancelPURequest() {
        return new CancelPURequest();
    }

    /**
     * Create an instance of {@link BookPUResponse }
     * 
     */
    public BookPUResponse createBookPUResponse() {
        return new BookPUResponse();
    }

}
